### PR TITLE
Clean up Travis test coverage

### PR DESCRIPTION
**Pull request by vmrob**
This patch revamps ci builds by adding support for a gcc (4.8, 4.9, 5, and 6), clang (3.4, 3.5, 3.6, 3.8, and 3.9), and Xcode (6.4, 7.3, and 8). It strips out many unnecessary components in the setup/build scripts, and adds code coverage with codecov.io.

Additionally, it removes a check from the any tests that is effectively undefined behavior and definitely fails on many release builds.

### CODE REVIEW

**Comment by vmrob** [comment]
What remains are two failing tests on gcc 4.9 that is [presumably] a compiler bug. I can't explain it and I think fixing it is outside the scope of this PR. Instead I wanted to make sure that the ci builds were working because I didn't feel comfortable relying on this product without that level of assurance.

**Comment by slurps-mad-rips** [comment]
Hi,

Thanks for your pull request.

It's been over a year since I had the core CI working (it was a much more massive configuration running on travis-ci's precise container approach. blech) and I was moving everything to the trusty build last night. I figured if anyone was using core, they wouldn't be constantly working against master, as I *thought* there were old branches for previous versions. Those were, for whatever reason, removed at some point. Most likely cherry picking changes between branches was more work than I wanted at the time and I got lazy. I cannot recall why otherwise. Your changes still miss out on a few requirements, such as clang with and without libc++ on linux, in both debug and release mode. I also had the install and before-install scripts setup in that way because it made parsing for errors easier (which I've gotten sometimes when a travis worker drops its internet connection somehow. It's rare but has happened)

The `.travis.yml` file is extremely old and was written back when core didn't just tag its releases but also had version branches. 

I'm willing to incorporate some of your changes but I'm currently working on getting Core back into some semblance of actually working and being usable by the community. This includes getting a CLA setup (MNMLSTC *is* a corporation). So for legal reasons I don't want to merge this *yet*. I'm hoping to have these legal changes taken care of by the end of today.

I was going to be adding the 4.8 and 4.9 changes in at some point, but getting those weird `CHECK(generic:13 == generic:13)` errors was driving me mad and I wanted to tackle that at some other time (though I believe I have a solution, and it means that `result<T>` is broken in its design, and might need an ABI break as part of the v2 changes).

The `any` test that you said involves undefined behavior does not actually involve that at all. When an object is moved from, it is in an unspecified but otherwise valid state (unless its state is specified, which we do in our move constructor). Considering my change where we set the member `f_` to 0 on move, the code will work correctly in release and debug builds.

I wasn't aware of codecov.io. It seems much nicer than coveralls.io.

One last thing: Your changes are not as exhaustive as I'm hoping to make the .travis.yml file before marking this as release 2.0. Previously I had libc++ support for clang on and off on linux. While your script does check to install libc++, it will never be used by cmake.

**Comment by vmrob** [comment]
Hi, thanks for the prompt response!

1) I would be happy to sign the CLA; just let me know where to find it.

2) As far as requirements goes, I was definitely aiming to compile both libc++ and the alternatives, but none of my efforts to compile without libc++ on clang would work due to what I presumed were standard library differences. I'm not nearly as familiar with CMake as I am with other build systems, but my cursory research indicated that CMake did respect `CXX` and `CXXFLAGS` which led me to believe that I was successfully compiling the product with libc++ (that and when I didn't use libc++ it would actually fail).

3) The `any` test fails on some compilers in some build variants on some particular platforms. I was incorrect in stating that it's undefined behavior, but being valid yet unspecified leaves the optimizer able to interpret what the state of the object should be post-move because there is no guarantee about what it should be. Just because 0 is assigned on move doesn't negate that valid-but-unspecified state.

**Comment by vmrob** [comment]
It takes a little while for these builds to run through, but I've rebased and pushed a modification I expect to fail in a few different places.

RE: `any`

It looks like the failing build I saw was on darwin in release. I don't have a link to the code, but the test failed here: https://travis-ci.org/vmrob/core/builds/166169677

RE: libc++

Clang 3.4 sans the `-stdlib=libc++` is failing. I'm probably not using the right standard libraries and it could probably be a little more explicit. I'm thinking variants with `libc++` and `libstdc++` might work out well. It looks like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56019 could explain the problem below.

```
In file included from /home/travis/build/vmrob/core/tests/memory.cpp:1:
/home/travis/build/vmrob/core/include/core/memory.hpp:148:39: error: no member
      named 'max_align_t' in namespace 'std'
  aligned_storage_t<N, alignof(::std::max_align_t)> data { };
                               ~~~~~~~^
/home/travis/build/vmrob/core/include/core/memory.hpp:148:24: warning: 
      'alignof' applied to an expression is a GNU extension
      [-Wgnu-alignof-expression]
  aligned_storage_t<N, alignof(::std::max_align_t)> data { };
                       ^
/home/travis/build/vmrob/core/include/core/memory.hpp:115:27: error: no member
      named 'max_align_t' in namespace 'std'
    return alignof(::std::max_align_t);
                   ~~~~~~~^
/home/travis/build/vmrob/core/include/core/memory.hpp:115:12: warning: 
      'alignof' applied to an expression is a GNU extension
      [-Wgnu-alignof-expression]
    return alignof(::std::max_align_t);
           ^
/home/travis/build/vmrob/core/include/core/memory.hpp:114:30: error: no return
      statement in constexpr function
  static constexpr size_type alignment () noexcept {
                             ^
2 warnings and 3 errors generated.
```

It appears this is the only one failing for the time being which does surprise me a little bit. I'll push a revision with those std variants and we'll see what happens.

**Comment by slurps-mad-rips** [comment]
I'll take a look in a moment, but I did try to push a fix to handle that `std::max_align_t` issue. You'll note in a recent change I made an alternative check to see if we're using clang and libstdc++4.8. If it's failing with clang 3.4 I'll try to take another look. For a while now, Core has had a libstdc++ hack definition to place the globally defined max_align_t into namespace std. It's frustrating for sure :)

**Comment by vmrob** [comment]
So just to reiterate what our goals are here:

- Test using both GCC and Clang
- Test various standard library configurations where possible
- Test Mac and Linux

We've got Clang and GCC as well as Mac and Linux--it's the standard libraries that are giving us trouble.

IIRC, we're not going to be able to easily get GCC to play nice with libc++, so we can nix that scenario. Instead, we're interested in getting Clang working with libc++ and libstdc++. To do this, the typical compilation command would be something like `clang++ -stdlib=libc++ ...` or `clang++ -stdlib=libstdc++`, right? If that's the case, I _think_ the modifications I've made in `scripts/travis-configure` should cover that scenario. Still waiting on travis results to confirm that we're able to build with those options.

**Comment by EricWF** [comment]
PS. The libc++ version provided by Ubuntu is criminally old AFAIK. I would suggest building it from trunk instead.

Here is [the script](https://github.com/ericniebler/range-v3/blob/master/install_libcxx.sh) I use to build and install libc++ for Travis. Also thee [range-v3](https://github.com/ericniebler/range-v3/)'s Travis configuration for example usage.

Let me know if I can provide any more information.

**Comment by vmrob** [comment]
Thanks, Eric. I'll take a look at that a bit later today.

**Comment by vmrob** [comment]
Hi, sorry for such a long delay. It appears that the current travis builds are pretty comprehensive and are all passing. Hopefully this PR helped a little bit with that effort, but either way, I think the end goal has been accomplished.

I'm going to go ahead and close this out, but if anything else is relevant here, please feel free to @mention me.

**Pull request closed without merging**
